### ISSUE TITLE
Any thought of expanding this to an N320?

### ISSUE THREAD

**Issue by garengllc** [DIFI-Consortium/rfnoc-difi#1]
I'd love to play with this some on an N320.  Any thoughts of porting it over down the line?

**Comment by 777arc** [comment]
Our X410 implementation is still in the prototype stage, and we don't have plans to target any other USRPs at the moment, but if anyone is able to get it working on a different USRP we will gladly include the implementation within this repo 😄

**Comment by 777arc** [comment]
see #2
