### ISSUE TITLE
Missing "difipack/standard_context_packet.hpp"

### ISSUE THREAD

**Issue by jpalladino** [DIFI-Consortium/rfnoc-difi#3]
Hello,
I'm trying to build the difi block controller, but it requires "difipack/standard_context_packet.hpp".
Line 7 of difi_block_control.cpp: ```#include <difipack/standard_context_packet.hpp>```

Is this missing from this repository, or is there another source for that?

Thank you,
Jim

**Comment by 777arc** [comment]
Ah nice catch, I just opened a PR that should include the missing headers

**Comment by jpalladino** [comment]
Great -- that was quick. Thanks!

**Comment by jpalladino** [comment]
Actually, are the associated cpp files missing as well?

Thanks,
Jim

**Comment by 777arc** [comment]
Looks like difipack was it's own library, back when it was created, so I've added it to the root of this repo

**Comment by jpalladino** [comment]
Thank you. I haven't tested it yet, but the block controller successfully builds now.
Jim
